name = "HardworkingTech"
license = "MIT"
licenselink = "https://github.com/salcan/BeyondNothing/blob/master/LICENSE"
description = "Blog about the future of development"
homepage = "https://hardworking.tech/"
min_version = 0.14
tags = ["blog", "lander", "minimalist", "clean"]
features = "nothing yet"
enableInlineShortcodes = true
baseURL = "/"

[author]
  name = "Jay Landro"
  homepage = "https://hardworking.tech/"
